#!/bin/bash

### openspace bash-framework v0.1.1 [https://github.com/openspace42/bash-framework]

os_bash_functions_version=0.1.4

################################################################################

define_vars() {

	########################################################################
	###################### Insert your variables here ######################
	########################################################################

	proj_name="Lorem-Ipsum-Dolor"
	short_name="lid"
	author_name="your_name_here"

	########################################################################

	os-define_vars

}

################################################################################

check_root() {

	if [[ $EUID -ne 0 ]]
	then
		echo "${r}${b}This script must be run as root${x}"
		echo
		echo "${b}Exiting...${x}"
		echo
		exit 1
	fi

}

download_os_functions() {

	clone_author=openspace42
	clone_name=bash-functions
	base_dir=/root/$clone_author
	clone_dir=$base_dir/$clone_name
	if [ -d $clone_dir ]
	then
		rm -r ${clone_dir:?}
	fi
	mkdir -p $base_dir
	( cd $base_dir && git clone https://github.com/$clone_author/$clone_name && cd $clone_name && if [ ! ${bleeding_edge_bf-null} = "-b" ]; then git checkout tags/v$os_bash_functions_version; fi &> /dev/null )

}

source_os_functions() {

	for f in /root/openspace42/bash-functions/functions/*
	do
		. $f
	done

}

################################################################################

################################################################################
######################## Insert project functions here #########################
################################################################################

################################################################################

perform_installation() {

	########################################################################
	################# Add your install-time functions here #################
	########################################################################

	########################################################################

}

################################################################################
