#!/usr/bin/env bash

### openspace bash-framework v0.1.7 [https://github.com/openspace42/bash-framework]

os_bash_functions_version=0.2.3

################################################################################

define_vars() {

	############################################################################
	######################## Insert your variables here ########################
	############################################################################

	proj_name="Lorem-Ipsum-Dolor"
	short_name="lid"
	author_name="your_name_here"
	git_host="https://github.com/"

	### Set this to `y` if your project stores no data on end users' machines that could go lost during a re-install or update
	skip_install_time_backup=n

	### Set this to the directory that has the most impactful size when performing a backup [such as `/var/www/` for nginx-related projects]
	backup_ref_dir="/path/to/ref/dir"

	############################################################################
	############################################################################
	############################################################################

	os-define_vars

}

################################################################################

check_root() {

	if [[ $EUID -ne 0 ]]
	then
		echo "This script must be run as root."
		echo
		echo "Exiting..."
		echo
		exit 1
	fi

}

download_os_functions() {

	clone_host="https://github.com"
	clone_author="openspace42"
	clone_name="bash-functions"

	clone_base_dir=/root/$clone_author
	clone_dir=$clone_base_dir/$clone_name

	mkdir -p $clone_base_dir

	if [ -d $clone_dir ]
	then
		rm -r ${clone_dir:?}
	fi

	( cd "$clone_base_dir" && git clone "$clone_host/$clone_author/$clone_name" && cd "$clone_name" && \
		if [ ! "${custom_bf-null}" = "e" ]; \
		then \
			git checkout "tags/v$os_bash_functions_version" && \
			echo "$os_bash_functions_version" > "./version_installed"; \
		else \
			clone_latest_commit="$(git log -n 1 --pretty=format:"%H"  | cut -c1-7)" && \
			echo "bleeding-edge-$clone_latest_commit" > "./version_installed"; \
		fi &> /dev/null \
	)

}

source_os_functions() {

	for f in /root/openspace42/bash-functions/functions/*
	do
		. $f
	done

}

################################################################################

################################################################################
######################## Insert project functions here #########################
################################################################################

################################################################################
################################################################################
################################################################################

perform_installation() {

	############################################################################
	################### Add your install-time functions here ###################
	############################################################################

	############################################################################
	############################################################################
	############################################################################

}

################################################################################
