#!/usr/bin/env bash

################################################################################

### Set bash environment error management

set -eu

### Add padding to output

echo

### Determine script execution directory, install directory, and source local functions file

exec_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

exec_dir_trim_2="$( echo ${exec_dir} | cut -f 1,2,3 -d'/')"
exec_dir_trim_3="$( echo ${exec_dir} | cut -f 1,2,3,4 -d'/')"

if [ -f "${exec_dir_trim_2}/functions" ]
then
	exec_dir_root="${exec_dir_trim_2}"
else
	if [ -f "${exec_dir_trim_3}/functions" ]
	then
		exec_dir_root="${exec_dir_trim_3}"
	else
		echo "Functions file not found in any second or third level parent directory of: | $exec_dir |"
		echo
        exit 1
	fi
fi

. "$exec_dir_root/functions"

### Check for root user runtime

check_root

### Evaluate command arguments for custom-version install

while getopts ":b:r:" arguments
do
    case $arguments in
        b)	export custom_dna_version="$OPTARG"
	        ;;
		r)	export custom_repo_code="$OPTARG"
	        ;;
        \?)	echo "Invalid option | -$OPTARG | for function | ${FUNCNAME[0]} |."
	        echo
	        exit
	        ;;
    esac
done
OPTIND=1

if [ ! -z "${custom_dna_version-}" ]
then
	case $custom_dna_version in
		e)	echo "Using bleeding-edge dna as per | -b e |."
			echo
			;;
		l)	echo "Disabling dna download and using local version as per | -b l |."
			echo
			;;
		*)	echo "Invalid content for | custom_dna_version | in function | ${FUNCNAME[0]} |."
			echo
			echo "Exiting..."
			echo
			exit
			;;
	esac
fi

if [ ! -z "${custom_repo_code-}" ]
then
	case $custom_repo_code in
		e)	echo "Using bleeding-edge repo code as per | -r e |."
			echo
			;;
		*)	echo "Invalid content for | custom_repo_code | in function | ${FUNCNAME[0]} |."
			echo
			echo "Exiting..."
			echo
			exit
			;;
	esac
fi

### Download and source openspace functions file

if [ ! "${custom_dna_version-null}" = "l" ]
then

    download_os_dna

fi

source_os_dna

### Define formatting

os-define_formatting

### Define variables

define_vars

################################################################################

### Actually run the installer

os-run_install
