#!/bin/bash

### openspace Bash-Framework v0.1.0 [https://github.com/openspace42/Bash-Framework]

################################################################################

### Set bash environment error management

set -e
set -u

### Source local functions file

echo
source_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. $source_dir/functions

### Source openspace functions file

source_os_functions

### Define formatting

os-define_formatting

### Define variables

define_vars

################################################################################

os-check_root

os-head_script

os-read_conf_settings

################################################################################
